/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clientevotacion;

import Votacion.Voto;
import java.io.ObjectOutputStream;
import java.net.Socket;

/**
 * Ventana principal del cliente de votación.
 *
 * Esta interfaz permite al usuario ingresar su identificación, token y
 * candidato, así como conectarse al servidor y enviar un voto.
 *
 * La ventana gestiona la comunicación con el servidor mediante un objeto
 * {@link ClienteConexion}, el cual mantiene un socket abierto para enviar votos
 * y recibir respuestas.
 */
/**
 *
 * @author Dylan
 */
public class VentanaCliente extends javax.swing.JFrame {

    private Socket socket;
    private ObjectOutputStream out;
    private ClienteConexion conexion;
    private boolean conectado = false;

    /**
     * Construye la ventana del cliente y prepara sus componentes gráficos. La
     * ventana se centra automáticamente en la pantalla.
     */
    public VentanaCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * Crea un objeto {@link Voto} usando los datos ingresados por el usuario en
     * los campos de texto y la fecha-hora actual.
     *
     * @return un objeto Voto formado con los datos del cliente
     */
    private Voto crearVoto() {
        String id = txtID.getText();
        String token = txtToken.getText();
        String candidato = comboCandidatos.getSelectedItem().toString();
        String fecha = java.time.LocalDateTime.now().toString();
        return new Voto(id, token, candidato, fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        txtToken = new javax.swing.JTextField();
        comboCandidatos = new javax.swing.JComboBox<>();
        lblMensaje = new javax.swing.JLabel();
        btnDesconectar = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();
        btnVotar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtToken.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        comboCandidatos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comboCandidatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juan", "María", "Pedro" }));
        comboCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCandidatosActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMensaje.setText(".");

        btnDesconectar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDesconectar.setForeground(new java.awt.Color(204, 0, 0));
        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        btnConectar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConectar.setForeground(new java.awt.Color(0, 204, 0));
        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        btnVotar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnVotar.setForeground(new java.awt.Color(0, 102, 102));
        btnVotar.setText("Votar");
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Candidatos:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Token:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID)
                    .addComponent(txtToken)
                    .addComponent(comboCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDesconectar)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensaje)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        // TODO add your handling code here:
        /**
         * Maneja el evento del botón "Votar".
         *
         * Valida la conexión al servidor, construye un voto con los datos
         * ingresados y lo envía mediante {@link ClienteConexion}. Luego muestra
         * el mensaje de respuesta recibido.
         */
        if (!conectado || conexion == null || !conexion.isAlive()) {
            lblMensaje.setText("No estás conectado al servidor");
            return;
        }

        try {
            String id = txtID.getText().trim();
            String token = txtToken.getText().trim();
            String candidato = comboCandidatos.getSelectedItem().toString();
            String fecha = java.time.LocalDateTime.now().toString();

            // Validaciones básicas
            if (id.isEmpty() || token.isEmpty() || candidato == null || candidato.isBlank()) {
                lblMensaje.setText("Completa ID, token y candidato.");
                return;
            }

            Votacion.Voto voto = new Votacion.Voto(id, token, candidato, fecha);

            String resultado = conexion.enviarVoto(voto);
            javax.swing.JOptionPane.showMessageDialog(this, resultado);
            lblMensaje.setText(resultado);

        } catch (Exception e) {
            lblMensaje.setText("Error al enviar voto: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnVotarActionPerformed

    private void comboCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCandidatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCandidatosActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        /**
         * Maneja el botón "Conectar".
         *
         * Intenta establecer una conexión con el servidor de votación. Si la
         * conexión se abre correctamente, se habilita el envío de votos.
         */
        try {
            conexion = new ClienteConexion("localhost", 5000);
            conectado = true;
            lblMensaje.setText("Conectado al servidor");
        } catch (Exception e) {
            conectado = false;
            lblMensaje.setText("Error al conectar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        // TODO add your handling code here:
        /**
         * Maneja el botón "Desconectar".
         *
         * Cierra la conexión existente con el servidor, libera recursos y
         * actualiza el estado de conexión.
         */
        if (conexion != null) {
            conexion.cerrar();
            conexion = null;
        }
        conectado = false;
        lblMensaje.setText("Desconectado del servidor");

    }//GEN-LAST:event_btnDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnVotar;
    private javax.swing.JComboBox<String> comboCandidatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtToken;
    // End of variables declaration//GEN-END:variables
}
